"""Добавил сурс и бюджет в БД

Revision ID: ee52130cf2d2
Revises: ed289029f037
Create Date: 2024-07-04 15:07:35.165850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee52130cf2d2'
down_revision = 'ed289029f037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_plan', schema=None) as batch_op:
        batch_op.drop_column('budget')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
